import './globals.css'
import Header from '../components/Header/page';
import Footer from '../components/Footer/page'
import { Providers } from "./providers";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'lxcste | Corebiz test',
  description: 'Generated by create next app',
}

/* En el root de la app, incluyo los componentes:
** - Header
** - Footer
** Para que se rendericen en todas las secciones de la tienda
 */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
